name: GitHub-Profile-3D-Contrib

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name quyen1303
          git config user.email quyennguyenvan0806@gmail.com
          git add -A .
          git commit -m "profile-3d"
          git push
